### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by Semir333** [tritter/homebridge-brewer#10]
Hello!

Plugin Error noticed. Crash homebridge
![Képernyőkép 2022-06-03 115114](https://user-images.githubusercontent.com/76537009/171831940-6a30489f-ffa5-4b05-8331-13c4b290986a.jpg)
.

**Comment by tritter** [comment]
@Semir333 In the error its stated that your bluetooth is off. "not poweredOn" Please check how to enable bluetooth on your Raspberry.

**Comment by Semir333** [comment]
Still same message. I think the problem is something else.

![image](https://user-images.githubusercontent.com/76537009/172901684-f47d744c-4046-4cce-bed6-a35bcf8cf8be.png)

**Comment by tritter** [comment]
@Semir333 could run `sudo hciconfig hci0 version `?

**Comment by Semir333** [comment]
![image](https://user-images.githubusercontent.com/76537009/172926580-d269207b-066d-4497-b2c6-60f9a6def761.png)

**Comment by tritter** [comment]
@Semir333 finally found some time to update. It may be fixed as I updated some libraries also the bluetooth one.

**Comment by Semir333** [comment]
Hi, the Homebridge now not blocked in totally, but the plugin have error. I've also not seen my Brewer still. (Config are okay)

![image](https://user-images.githubusercontent.com/76537009/203937307-90a5d2c1-c5a3-4248-a3d5-0769aed4d40b.png)

**Comment by Semir333** [comment]
![image](https://user-images.githubusercontent.com/76537009/203977841-0cf2b4c2-a487-4d9a-b3eb-d59cb714d185.png)

**Comment by Semir333** [comment]
![image](https://user-images.githubusercontent.com/76537009/203979017-a883ec60-98ce-49c9-8359-1e0174ca96f5.png)

Now have some BT issue? :S BT is activated.

![image](https://user-images.githubusercontent.com/76537009/203979701-75578e4c-d473-4d5b-81ee-07e11c288d94.png)
![image](https://user-images.githubusercontent.com/76537009/203981976-414b208f-7fdb-44d7-9ede-21f38034bf60.png)

**Comment by tritter** [comment]
@Semir333 really weird, did you try the v.2.1.0?

**Comment by Semir333** [comment]
Yes installed.

**Comment by tritter** [comment]
@Semir333 did you try these steps? https://github.com/noble/noble/issues/35, https://github.com/noble/node-bluetooth-hci-socket/issues/110 I use a plugin called noble, the problem is that I don't control that stack. The errors seem all to come from noble, so you could do some research upon that. Otherwise when you don't understand all technical details it may be an option to use a freshly installed raspberry pi which has bluetooth on board?

**Comment by Semir333** [comment]
I'm not understand the writings very well there. I'm use internal BT, not external (so it's on board) but the freshly installing is not an option because my whole house using the pie ^^
