### ISSUE TITLE
Keurig support

### ISSUE THREAD

**Issue by danfratamico** [tritter/homebridge-brewer#11]
**Is your feature request related to a problem? Please describe:**
No, wondering if Keurig support is in the pipeline.

**Describe the solution you'd like:**
Keurig support for SMART brewers.

**Describe alternatives you've considered:**
N/A

**Additional context:**
N/A

**Comment by tritter** [comment]
@danfratamico unfortunately no, the protocol is very specific for this generation of Nespresso devices. Even the new ones it isn't possible anymore to use the app and brew coffee. It seems like the industry don't see the benefit in smart coffee makers :( Best is to buy a second hand 'Nespresso Expert'
