### ISSUE TITLE
Working in Conjunction With Other Noble/Bluetooth Devices on The Same Pi/Homebridge

### ISSUE THREAD

**Issue by Brett-R-Turner** [tritter/homebridge-brewer#3]
**Describe Your Problem:**
Heyo; This isnt exactly an issue with your plugin, but a higher level issue I'm hoping you can help me resolve to allow your plugin to work smoother alongside my others. 

I have been using brewer for a few months now and have it running in some wicked cool automation (My fave being having it trigger a cup of coffee and cancel it to heat up the machine 1 minute before my alarm, then pouring the cup when I get out of bed based on a pressure sensor under my mattress). Anyway.

I recently installed a plugin that uses the same Noble protocol to connect to my SOMA smart shades, at first all was well however as soon as I tried to use the brewer home bridge went crazy on me, essentially not being able to connect to either device. I've done some digging and it seems the issue is that noble can effectively only do one thing at once. This information was gathered from this support thread in the SOMA repo https://github.com/fisherwise/homebridge-soma-shades/issues/2, and then this further link more detailing the problem that someone posted in the respective thread. https://github.com/abandonware/noble/issues/26
I would normally be bugging those guys, however the dev seems to be inactive there. 

From what I understand based on the second link I posted there, the solution would be to connect a USB adapter to the Pi, and have one plugin use the onboard adapter, and one use the external USB adapter. 

I'm somewhat savvy, however when it comes to dealing with things like noble, and even worse, noble integrated within a homebrdige plugin, I'd be at a loss as far as how to do this. I'd figure as someone who has dealt with both of these in building a rather fanatic plugin, you may. be able to help. Would be happy to send a coffee or two your way/a tip of some sort in return for the help here if you are willing.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by tritter** [comment]
@Brett-R-Turner Yes that's true, just one device is possible with the Raspberry's limitation together with noble. I tried to find other plugins but for now noble is the only cross-platform working solution. And works "stable" enough for most plugins.

In your case, I would just add more raspberries, the cost is really low (zero W). Just run multiple homebridge instances, I'm also running around 8, thats no problem at all! This will make your homebridge environment much more stable!
One other possible problem of homebridge is that every plugin needs to "wait" for each other. You could try to use a bridge for my plugin or the soma plugin (https://github.com/homebridge/homebridge/wiki/Child-Bridges)?

Unfortunately I don't have the SOMA devices/experience. Also keep in mind that there is a hardware limit of around 5 devices to connect simultaneously.
