### ISSUE TITLE
Wifi support

### ISSUE THREAD

**Issue by jsholiday** [tritter/homebridge-brewer#4]
Does this plugin support wifi on the Vertuo Next model?

**Comment by tritter** [comment]
HI @jsholiday,

No it doesn't, I also tried to use the same bluetooth stack. It seems to be equal I think I could theoretically get the water status on the Vuerto Next. But as you can see inside the Nespresso App, its not possible to brew coffee within the app or even schedule it. I think the decision of this has to be with the cup which is then punctured already hours before the actual brew. I don't know where Nespresso is heading with this machine and their connectivity. I also don't have any idea what the Wifi chip is doing at the moment? Updating the internal recipes or so?

If you have any ideas or any info please let me know!

Cheers,
Thom

**Comment by jsholiday** [comment]
Hi @tritter! 

I think you're right on this. I've had the Vertuo Next for about a week now. I've been monitoring its network activity on my router and it seems that it only makes a wifi connection when either: 

A) The app makes a Bluetooth connection to the unit 
OR 
B) The unit is powered on by pressing the brew button to wake from auto sleep. 

It seems that when in auto sleep, the wifi connection to my router is dropped. 
This leads me to believe that the unit is also using wifi to check for firmware updates in the app and/or new recipes/new pods types when first powered on. 

Kinda bummed there isn't more smart functionality here from Nespresso as it seems like it'd be pretty easy with Bluetooth and wifi on board. But at least it makes a great drink! 

Thanks for your response.
