### ISSUE TITLE
brewer and Monterey

### ISSUE THREAD

**Issue by bubez81** [tritter/homebridge-brewer#6]
Hello, did you notice problems with macOS Monterey? 
Now I receive this message
`libc++abi: terminating with uncaught exception of type Napi::Error: Attempt to access memory outside buffer bounds`
and homebridge reboots continuously. if I disable bluetooth and then re-enable it, homebridge restarts but the plugin is no longer able to connect to nespresso

**Comment by tritter** [comment]
@bubez81 Hi Michele,
I didnt have a chance to look into this, but I updated my Mac at least to Monterey. There also seem some discovery issues still (https://github.com/abandonware/noble/issues/225)
Probably a fix of the bluetooth library where we/I need to wait for is needed. Easiest is to get a raspberry pi maybe in the meantime? :)

Greets,
Thom

**Comment by bubez81** [comment]
Hello!
ok then for the moment we just have to wait or switch to a raspberry momentarily

**Comment by tritter** [comment]
Hi @bubez81 I know almost a year again 😑 finally updated it works for me now on a m1!

**Comment by bubez81** [comment]
Wow thank you!!
