### ISSUE TITLE
Token generation not work

### ISSUE THREAD

**Issue by Semir333** [tritter/homebridge-brewer#9]
Hello! Shell command not working. What am i do wrong? File copied to C:, adminsitrator mode okay.

PS C:\> hexdump -v -e '/1 "%02X "' btsnoop_hci.log | grep -o '0B 00 04 00 12 14 00 \<.. .. .. .. .. .. .. ..\>'
hexdump : The term 'hexdump' is not recognized as the name of a cmdlet, function, script file, or operable program. Che
ck the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ hexdump -v -e '/1 "%02X "' btsnoop_hci.log | grep -o '0B 00 04 00 12  ...
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (hexdump:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by tritter** [comment]
hexdump is not available PowerShell (windows) as stated in the error. Please use unix or linux to execute hexdump commands.
